name: Github Actions Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
      - name: what's in the system?
        run: |
          echo "whoami"
          whoami
          echo "pwd"
          pwd
          echo "ls -la"
          ls -la
          echo "java -version"
          java -version
          echo "git --version"
          git --version
          echo
          echo "RUNNER_WORKSPACE"
          echo $RUNNER_WORKSPACE
          echo
          echo "env"
          env
